//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanXuatCheckList.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checklist_JobStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Checklist_JobStep()
        {
            this.Checklist_Job = new HashSet<Checklist_Job>();
        }
    
        public int Id { get; set; }
        public int ChecklistId { get; set; }
        public int StepIndex { get; set; }
        public string Name { get; set; }
        public string JobStepContent { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string RelatedEmployees { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> RealEndDate { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public double Quantities { get; set; }
        public double RealQuantities { get; set; }
        public int StatusId { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Checklist Checklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checklist_Job> Checklist_Job { get; set; }
        public virtual SUser SUser { get; set; }
        public virtual Status Status { get; set; }
    }
}
