//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanXuatCheckList.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checklist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Checklist()
        {
            this.Checklist_JobStep = new HashSet<Checklist_JobStep>();
        }
    
        public int Id { get; set; }
        public int TemplateId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> POId { get; set; }
        public int ObjectType { get; set; }
        public string Name { get; set; }
        public Nullable<int> LineId { get; set; }
        public double ProductionDays { get; set; }
        public int Quantities { get; set; }
        public double Productivity { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> InputDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> RealEndDate { get; set; }
        public string RelatedEmployees { get; set; }
        public int StatusId { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checklist_JobStep> Checklist_JobStep { get; set; }
        public virtual PO_Sell PO_Sell { get; set; }
        public virtual Status Status { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Line Line { get; set; }
        public virtual Product Product { get; set; }
        public virtual Template_Checklist Template_Checklist { get; set; }
    }
}
