//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanXuatCheckList.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Checklist = new HashSet<Checklist>();
            this.Order = new HashSet<Order>();
            this.PO_Sell = new HashSet<PO_Sell>();
            this.Product = new HashSet<Product>();
            this.Delivery = new HashSet<Delivery>();
            this.ProductionBatch = new HashSet<ProductionBatch>();
            this.Receiption = new HashSet<Receiption>();
        }
    
        public int Id { get; set; }
        public int Index { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public string Fax { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Address { get; set; }
        public string Representative { get; set; }
        public string TaxCode { get; set; }
        public string BankAccount { get; set; }
        public string CardNumber { get; set; }
        public string DefaultAccount { get; set; }
        public string DefaultAccountCode { get; set; }
        public string CreditAccount { get; set; }
        public Nullable<double> DebitLimitStandard { get; set; }
        public Nullable<double> DebitLimitAllow { get; set; }
        public Nullable<double> UpAdjust { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedUser { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checklist> Checklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_Sell> PO_Sell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delivery> Delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductionBatch> ProductionBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receiption> Receiption { get; set; }
    }
}
