//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanXuatCheckList.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SanXuatCheckListEntities : DbContext
    {
        public SanXuatCheckListEntities()
            : base("name=SanXuatCheckListEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Checklist> Checklist { get; set; }
        public virtual DbSet<Checklist_Job> Checklist_Job { get; set; }
        public virtual DbSet<Checklist_Job_ActionLog> Checklist_Job_ActionLog { get; set; }
        public virtual DbSet<Checklist_Job_Alert> Checklist_Job_Alert { get; set; }
        public virtual DbSet<Checklist_Job_Attachment> Checklist_Job_Attachment { get; set; }
        public virtual DbSet<Checklist_Job_Comment> Checklist_Job_Comment { get; set; }
        public virtual DbSet<Checklist_Job_EmployeeReference> Checklist_Job_EmployeeReference { get; set; }
        public virtual DbSet<Checklist_Job_Error> Checklist_Job_Error { get; set; }
        public virtual DbSet<Checklist_Job_NotifyLog> Checklist_Job_NotifyLog { get; set; }
        public virtual DbSet<Checklist_JobStep> Checklist_JobStep { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Delivery> Delivery { get; set; }
        public virtual DbSet<DeliveryDetail> DeliveryDetail { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Line> Line { get; set; }
        public virtual DbSet<LotSupplies> LotSupplies { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialNorms> MaterialNorms { get; set; }
        public virtual DbSet<MaterialType> MaterialType { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<OrderDetail> OrderDetail { get; set; }
        public virtual DbSet<P_Config> P_Config { get; set; }
        public virtual DbSet<PO_Sell> PO_Sell { get; set; }
        public virtual DbSet<PO_SellDetail> PO_SellDetail { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductionBatch> ProductionBatch { get; set; }
        public virtual DbSet<ProductionFile> ProductionFile { get; set; }
        public virtual DbSet<ProFileControl> ProFileControl { get; set; }
        public virtual DbSet<Receiption> Receiption { get; set; }
        public virtual DbSet<ReceiptionDetail> ReceiptionDetail { get; set; }
        public virtual DbSet<SCategory> SCategory { get; set; }
        public virtual DbSet<SCompany> SCompany { get; set; }
        public virtual DbSet<SCompanyModule> SCompanyModule { get; set; }
        public virtual DbSet<SConfig> SConfig { get; set; }
        public virtual DbSet<SFeature> SFeature { get; set; }
        public virtual DbSet<Size> Size { get; set; }
        public virtual DbSet<SLevelCompany> SLevelCompany { get; set; }
        public virtual DbSet<SMenu> SMenu { get; set; }
        public virtual DbSet<SModule> SModule { get; set; }
        public virtual DbSet<SPermission> SPermission { get; set; }
        public virtual DbSet<SRoLe> SRoLe { get; set; }
        public virtual DbSet<SRolePermission> SRolePermission { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StatusType> StatusType { get; set; }
        public virtual DbSet<SUser> SUser { get; set; }
        public virtual DbSet<SUserRole> SUserRole { get; set; }
        public virtual DbSet<T_Equipment> T_Equipment { get; set; }
        public virtual DbSet<T_EquipmentAttribute> T_EquipmentAttribute { get; set; }
        public virtual DbSet<T_EquipmentGroup> T_EquipmentGroup { get; set; }
        public virtual DbSet<T_EquipmentType> T_EquipmentType { get; set; }
        public virtual DbSet<T_EquipmentTypeAttribute> T_EquipmentTypeAttribute { get; set; }
        public virtual DbSet<T_EquipType_Default> T_EquipType_Default { get; set; }
        public virtual DbSet<T_EquipTypeAttr_Default> T_EquipTypeAttr_Default { get; set; }
        public virtual DbSet<Template_Checklist> Template_Checklist { get; set; }
        public virtual DbSet<Template_CL_Job> Template_CL_Job { get; set; }
        public virtual DbSet<Template_CL_JobStep> Template_CL_JobStep { get; set; }
        public virtual DbSet<TemplateControl> TemplateControl { get; set; }
        public virtual DbSet<TemplateFile> TemplateFile { get; set; }
        public virtual DbSet<TemplateFileType> TemplateFileType { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<UnitType> UnitType { get; set; }
        public virtual DbSet<W_Config> W_Config { get; set; }
        public virtual DbSet<WareHouse> WareHouse { get; set; }
        public virtual DbSet<WorkShop> WorkShop { get; set; }
    }
}
