//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanXuatCheckList.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMenu
    {
        public int Id { get; set; }
        public int MenuCategoryId { get; set; }
        public string MenuName { get; set; }
        public int OrderIndex { get; set; }
        public string Link { get; set; }
        public bool IsShow { get; set; }
        public bool IsViewIcon { get; set; }
        public string Icon { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public int ModuleId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public int CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual SCategory SCategory { get; set; }
        public virtual SModule SModule { get; set; }
    }
}
